### PR TITLE
Updating dependencies for angular 13 and adding imports to public_api.ts

### PR DESCRIPTION
**Pull request by jsrosas**
- Update library and app to Angular13
- Exporting classes exposed by module but not by entry point.

### CODE REVIEW

**Comment by davidwalschots** [comment]
Thank you for your contribution! I am wondering what use case you are running into that requires exporting the `ValidationMessageComponent`, `FormDirective`, and `ValidationMessagesComponent` types?

**Comment by jsrosas** [comment]
During npm run build:lib
× Compiling with Angular sources in Ivy partial compilation mode.
angular-reactive-validation/src/validation-message/validation-message.component.ts:18:14 - error NG3001: Unsupported private class ValidationMessageComponent. This class is visible to consumers via ReactiveValidationModule -> ValidationMessageComponent, but is not exported from the top-level library entrypoint.

18 export class ValidationMessageComponent implements OnInit {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~
angular-reactive-validation/src/form/form.directive.ts:12:14 - error NG3001: Unsupported private class FormDirective. This class is visible to consumers via ReactiveValidationModule -> FormDirective, but is not exported from the top-level library entrypoint.

12 export class FormDirective {
                ~~~~~~~~~~~~~~
angular-reactive-validation/src/validation-messages/validation-messages.component.ts:24:14 - error NG3001: Unsupported private class ValidationMessagesComponent. This class is visible to consumers via ReactiveValidationModule -> ValidationMessagesComponent, but is not exported from the top-level library entrypoint.

24 export class ValidationMessagesComponent implements AfterContentInit, OnDestroy, OnInit {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by davidwalschots** [comment]
Interesting. It's a shame exposing these is now necessary, as users of this library shouldn't care about those internals, just about using them inside HTML. Angular will be Angular I guess 😀.

**Comment by jsrosas** [comment]
Yeah indeed.

**Pull request merged**
